# Extracted from ALINX 24_smg_interface_demo.rar: smg_interface.xdc
set_property PACKAGE_PIN J5 [get_ports {SMG_Data[0]}]
set_property PACKAGE_PIN M3 [get_ports {SMG_Data[1]}]
set_property PACKAGE_PIN J6 [get_ports {SMG_Data[2]}]
set_property PACKAGE_PIN H5 [get_ports {SMG_Data[3]}]
set_property PACKAGE_PIN G4 [get_ports {SMG_Data[4]}]
set_property PACKAGE_PIN K6 [get_ports {SMG_Data[5]}]
set_property PACKAGE_PIN K3 [get_ports {SMG_Data[6]}]
set_property PACKAGE_PIN H4 [get_ports {SMG_Data[7]}]
set_property PACKAGE_PIN M2 [get_ports {Scan_Sig[0]}]
set_property PACKAGE_PIN N4 [get_ports {Scan_Sig[1]}]
set_property PACKAGE_PIN L5 [get_ports {Scan_Sig[2]}]
set_property PACKAGE_PIN L4 [get_ports {Scan_Sig[3]}]
set_property PACKAGE_PIN M16 [get_ports {Scan_Sig[4]}]
set_property PACKAGE_PIN M17 [get_ports {Scan_Sig[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Scan_Sig[*]}]
