#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

#define RT_NAME_MAX 16
#define RT_ALIGN_SIZE 16
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 100

#define RT_USING_SEMAPHORE
#define RT_USING_CONSOLE
#define RT_USING_TINY_PRINTF
#define RT_CONSOLEBUF_SIZE 128
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_USING_SYMTAB
#define FINSH_USING_DESCRIPTION
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 32768
#define FINSH_CMD_SIZE 80
#define FINSH_ARG_MAX 8

#define IDLE_THREAD_STACK_SIZE 1024
#define RT_VER_NUM 0x30105

#endif
