name: Auto-test Workflow

on:
  push:
    branches: [main]
    paths:
      - 'npc/**'
      - 'patch/**'
      - '.github/**'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      comment:
        description: '注释 (可为空)'
        required: false
        default: ''

run-name: >-
  ${{
    github.event_name == 'push' && github.event.head_commit.message ||
    github.event_name == 'pull_request' && github.event.pull_request.title ||
    github.event.inputs.comment != '' && github.event.inputs.comment ||
    'Manual trigger'
  }}

permissions:
  contents: read
  issues: write

env:
  OSS_CAD_SUITE_RELEASE_TAG: 2025-11-24

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    secrets: inherit

  hello:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          JYD_HOME: ${{ needs.setup.outputs.JYD_HOME }}
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}

      - name: hello
        run: |
          KEY=$(head -c 5 /dev/urandom | base32)
          python $MONITOR_PY --middle="Hello, AbstractMachine!" --good=$KEY make ARCH=riscv32-jyd -C $JYD_HOME/am-kernels/kernels/hello run mainargs=$KEY

  basic-tests:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        test-set:
          - dir: am-kernels/tests/cpu-tests
            args: ""
          - dir: riscv-tests-am
            args: "TEST_ISA=i"
          - dir: riscv-arch-test-am
            args: "TEST_ISA=I"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          JYD_HOME: ${{ needs.setup.outputs.JYD_HOME }}
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}

      - name: Make Binary
        run: |
          # make sim binary first to avoid parallel build issue
          make ARCH=riscv32-jyd -C $JYD_HOME/npc

      - name: Run basic test (${{ matrix.test-set.dir }})
        run: |
          make ARCH=riscv32-jyd -C $JYD_HOME/${{ matrix.test-set.dir }} run ${{ matrix.test-set.args }}

  rt-thread:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          JYD_HOME: ${{ needs.setup.outputs.JYD_HOME }}
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}

      - name: Install dependency
        run: sudo apt install -y scons

      - name: rt-thread
        run: |
          cd $JYD_HOME/rt-thread-am/bsp/abstract-machine
          make ARCH=riscv32-jyd init
          KEY=$(head -c 5 /dev/urandom | base32)
          python $MONITOR_PY --good=$KEY make ARCH=riscv32-jyd run

  yosys-sta:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          JYD_HOME: ${{ needs.setup.outputs.JYD_HOME }}
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}
          install-toolchain: 'false'

      - name: Install dependency
        run: |
          sudo apt install -y libunwind-dev liblzma-dev

      - name: Clone yosys-sta
        run: |
          git clone -b ci https://github.com/OSCPU/yosys-sta
          cd yosys-sta
          make init
          echo exit | ./bin/iEDA -v

      - name: Generate Verilog
        run: |
          make -C $JYD_NPC_HOME verilog

      - name: Set environment variables
        run: |
          echo "VFILE=${{ needs.setup.outputs.VFILE }}" >> $GITHUB_ENV
          echo "DESIGN=${{ needs.setup.outputs.DESIGN }}" >> $GITHUB_ENV

      - name: Run STA
        run: |
          make -C yosys-sta sta DESIGN=$DESIGN CLK_FREQ_MHZ=500 CLK_PORT_NAME=clock RTL_FILES=$VFILE

      - name: Check latch
        run: |
          YOSYS_LOG=yosys-sta/result/$DESIGN-500MHz/synth_stat.txt
          if grep "DLL\|DLH" $YOSYS_LOG ; then
            echo "The design contains latch, which is not allowed."
            false
          fi

      - name: Parse area
        run: |
          YOSYS_LOG=yosys-sta/result/$DESIGN-500MHz/yosys-fixed.log
          AREA=`grep -o "Chip area for module .*: .*" $YOSYS_LOG | sed -e 's/.*: \([0-9]*\.[0-9]*\)$/\1/'`
          if [[ $AREA == "" ]] ; then
            echo "Can not obtain area from yosys-sta. Abort."
            false
          fi
          echo "Area: $AREA"
          echo "AREA=$AREA" >> $GITHUB_ENV

      - name: Upload STA result
        uses: actions/upload-artifact@v6
        with:
          name: sta-result
          path: yosys-sta/result/${{ needs.setup.outputs.DESIGN }}-500MHz

      - name: Upload netlist file
        uses: actions/upload-artifact@v6
        with:
          name: netlist
          path: yosys-sta/result/${{ needs.setup.outputs.DESIGN }}-500MHz/${{ needs.setup.outputs.DESIGN }}.netlist.fixed.v
