name: Auto-test Workflow

on:
  push:
    branches: [main]
    paths:
      - 'npc/**'
      - 'patch/**'
      - 'abstract-machine/**'
      - 'jyd-tests/**'
      - '.github/**'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      comment:
        description: '注释 (可为空)'
        required: false
        default: ''

run-name: >-
  ${{
    github.event_name == 'push' && github.event.head_commit.message ||
    github.event_name == 'pull_request' && github.event.pull_request.title ||
    github.event.inputs.comment != '' && github.event.inputs.comment ||
    'Manual trigger'
  }}

permissions:
  contents: read
  issues: write

env:
  OSS_CAD_SUITE_RELEASE_TAG: 2025-11-24

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    secrets: inherit

  hello:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}

      - name: hello
        run: |
          KEY=$(head -c 5 /dev/urandom | base32)
          python $MONITOR_PY --middle="Hello, AbstractMachine!" --good=$KEY make ARCH=riscv32-jyd -C am-kernels/kernels/hello run mainargs=$KEY

  basic-tests:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        test-set:
          - dir: am-kernels/tests/cpu-tests
            args: ""
            precompile: true
          - dir: riscv-tests-am
            args: "TEST_ISA=i"
            precompile: true
          - dir: riscv-arch-test-am-jyd
            args: 'TEST_ISA="I M Zicsr"'
            precompile: false
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}

      - name: Make Binary
        run: |
          # make sim binary first to avoid parallel build issue
          make ARCH=riscv32-jyd -C npc

      - name: Make precompile test set
        if: matrix.test-set.precompile
        run: |
          make ARCH=riscv32-jyd -C ${{ matrix.test-set.dir }}

      - name: Run basic test (${{ matrix.test-set.dir }})
        run: |
          make ARCH=riscv32-jyd -C ${{ matrix.test-set.dir }} run ${{ matrix.test-set.args }}

  rtthread-nano:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}

      - name: Build NPC sim
        run: |
          make ARCH=riscv32-jyd -C npc

      - name: Build rtthread-nano image
        run: |
          make ARCH=riscv32-jyd -C jyd-tests/rtthread-nano

      - name: rtthread-nano
        run: |
          python $MONITOR_PY make ARCH=riscv32-jyd -C jyd-tests/rtthread-nano run

  coremark:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common operations
        uses: ./.github/actions/common
        with:
          MAKEFLAGS: ${{ needs.setup.outputs.MAKEFLAGS }}

      - name: Install dependency
        run: sudo apt install -y g++-13 gcc-13-plugin-dev libgmp-dev

      - name: Build NPC sim
        run: |
          make ARCH=riscv32-jyd -C npc

      - name: coremark
        run: |
          make ARCH=riscv32-jyd -C jyd-tests/coremark-official HOST_CXX=g++-13 run VSIM_print_fullperf=1
